### ISSUE TITLE
Erreur "Cannot open database because the directory does not exist"

### ISSUE THREAD

**Issue by azgar44** [Victor2106/Pronote-bot#1]
En essayant de faire fonctionner le bot **toutes les commandes de l'ent (du dossier commandes) me font la même erreur : "Cannot open database because the directory does not exist"**, du coup le bot ne fonctionne pas.

**Comment by Victor2106** [comment]
Il faut créer un dossier data à la racine du bot.
Une fois créer il faut créer un dossier pronote dans celui-ci
